# Generated by Django 3.0 on 2024-07-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcompany',
            name='Company_GST',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addcompany',
            name='Company_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addcompany',
            name='Company_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addcompany',
            name='Company_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='additem',
            name='Category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='additem',
            name='Item_GST',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='additem',
            name='Item_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='additem',
            name='Item_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='additem',
            name='Item_price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addtable',
            name='Category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addtable',
            name='Table_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itembill',
            name='bill_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itembill',
            name='gst',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='itembill',
            name='item_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itembill',
            name='item_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itembill',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='itembill',
            name='table_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itembill',
            name='tax_amt',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='itembill',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='itembill',
            name='total_gst',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='utype',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='usertype',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
