# Generated by Django 3.0 on 2024-07-02 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_auto_20240701_1856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemBill',
            new_name='ItemOrder',
        ),
    ]
