# Generated by Django 3.0 on 2024-07-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0005_pracel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracel',
            name='pracel_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
