# Generated by Django 3.0 on 2024-07-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0006_pracel_pracel_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='item_cat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='item_cat',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
